import { useState, useEffect } from 'react';
import Head from 'next/head';
import Student from '../components/Student';

export default function Home({ data }) {
  const [filterString, setFilterString] = useState('');
  const [filterTag, setFilterTag] = useState('');
  const [filteredArray, setFilteredArray] = useState([])

  const array = data.students.map((item) => {
    item.fullName = `${item.firstName} ${item.lastName}`;
    item.tagNames = [];
    return item;
  });

  //item.tagNames.includes(filterTag);

  const filterArray = array
    .filter((item) => 
      item.fullName.toLowerCase().includes(filterString)
    )
    // .filter((item) => item.tagNames.includes(filterTag))
    .map((item, idx) => <Student array={array} item={item} key={idx} />)

  const nameHandler = (e) => {
    setFilterString(e.target.value);
  };

  const tagHandler = (e) => {
    setFilterTag(e.target.value);
  };

  return (
    <div class='bg-gray-300 flex justify-center'>
      <Head>
        <title>Assessment - Circle Medical</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div class='lg:w-1/2 mt-28'>
        <div class='bg-white flex flex-col'>
          <input
            type='text'
            placeholder='Search by Name'
            class='m-2 p-2 border-b-2 hover:border-gray-400 focus:border-gray-400 disabled:opacity-75'
            onChange={nameHandler}
          />
          <input
            type='text'
            placeholder='Search by Tag'
            class='m-2 p-2 border-b-2 hover:border-gray-400 focus:border-gray-400 disabled:opacity-75'
            onChange={tagHandler}
          />
        </div>
        <div class='bg-white h-screen overflow-auto'>{filterArray}</div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`https://api.hatchways.io/assessment/students`);
  const data = await res.json();

  return { props: { data } };
}
