import Head from 'next/head'
import Student from '../components/Student'

export default function Home({data}) {
  console.log(data.students)
  return (
    <div >
      <Head>
        <title>Assessment - Circle Medical</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data.students.map((item, idx) => (
          <Student item={item} key={idx} />
        ))}
      </main>
    </div>
  )
}


export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://api.hatchways.io/assessment/students`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}