import Head from 'next/head';
import Student from '../components/Student';

export default function Home({ data }) {
  console.log(data.students);
  return (
    <div class='bg-gray-200'>
      <Head>
        <title>Assessment - Circle Medical</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div class='lg:px-40 lg:spy-20 bg-white'>
        <main class=''>
          {data.students.map((item, idx) => (
            <Student item={item} key={idx} />
          ))}
        </main>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://api.hatchways.io/assessment/students`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
